### ISSUE TITLE
Does not compile on rustc 1.59.0-nightly

### ISSUE THREAD

**Issue by cgrenz** [strake/null-terminated.rs#6]
```
error[E0658]: dereferencing raw mutable pointers in constant functions is unstable
   --> /…/null-terminated-0.3.16/src/lib.rs:339:72
    |
339 |     pub const unsafe fn new_unchecked(p: *const u8) -> &'static Self { &*(p as *mut Self) }
    |                                                                        ^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
    = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
```

**Comment by strake** [comment]
The newly-published version 0.3.16 should be buildable.

**Comment by cgrenz** [comment]
Thanks! The code in `master` now compiles, but sadly version 0.3.16 on crates.io still has the compile error.

**Comment by strake** [comment]
Ah indeed, sorry, try version 0.3.17.
